### ISSUE TITLE
Not works, no output. 

### ISSUE THREAD

**Issue by DonikaV** [sudo-suhas/lint-staged-multi-pkg#3] opened 2019-03-20 11:41 UTC
root folder 
```
"lerna": "3.11.0",
"husky": "^1.3.1"
```
lerna.json 

```
"packages": [
    "pack1",
    "pack2"
  ],
```

pack 1 and pack2 have this in package.json in scripts

`"precommit": "lint-staged"`

With .lintstagedrc.yml 

```yml
linters:
  "src/main/js/**/*.js":
    - "eslint src/main/js --fix"       
    - "prettier --print-width 120 --tab-width 4 --trailing-comma none --write src/main/js/**/*.js"                    
    - "git add"
```

After commit nothing.  I mean no any messages/output

It works only from terminal. 
I mean i need run 
git add -A
npm run -s precommit

But if i do normat flow for commit - nothing

**Comment by sudo-suhas** [comment] 2019-03-21 05:49
What do you mean exactly by `normal flow`?

**Comment by DonikaV** [comment] 2019-03-21 09:10
gid add -A commit -m "my message" 

expected - hook executed, but nothing happens

**Comment by sudo-suhas** [comment] 2019-03-21 09:11
Can you create a minimal git repo which demonstrates the issue?

**Comment by sudo-suhas** [comment] 2019-03-21 09:12
From what I can tell, you have not configured `husky` correctly. See https://github.com/typicode/husky#upgrading-from-014

**Comment by DonikaV** [comment] 2019-03-21 09:17
with this module it works 
https://www.npmjs.com/package/pre-commit
```
"scripts": {
"precommit": "lerna run --concurrency 1 --stream precommit"
}
```

```
"pre-commit": [
		"precommit"
	],
```

i will check again  your docs, thanks

**Comment by sudo-suhas** [comment] 2019-03-21 09:19
The `husky` confirmation is the problem as I suspected. Closing this issue as we identified the cause.

**Closed as completed by sudo-suhas** 2019-03-21 09:19 UTC
